### ISSUE TITLE
Point to this repository from EE4J Developer Resources

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jsonp#1]
The "Developer Resources" tab of the EE4J project information https://projects.eclipse.org/projects/ee4j.jsonp/developer is meant for links like the one to this GitHub repository. It is currently empty. The metainformation should be updated.

**Comment by waynebeaton** [comment]
Fixed.

**Comment by keilw** [comment]
Great, thanks. Before opening other tickets, are there plans to publish some EE4J site on GitHub or via another TLD (like MicroProfile.io) some time or will it use Eclipse.org for now? Science or IoT show what a TLD can do, maybe that's where EE4J might head over time? The old JavaEE gh-pages has content valuable to JSON-P but I want to find out where the best place will be to make that available?

**Comment by waynebeaton** [comment]
The focus right now is to get the code into the repository. Websites are coming up. Stay tuned.
