### ISSUE TITLE
Small mistake in documentation of javax.json.stream.JsonGenerator

### ISSUE THREAD

**Issue by jjspiegel** [eclipse-ee4j/jsonp#106]
The following text is found on many of the single-value write methods of JsonGenerator:
@throws JsonGenerationException if this method is not called within an array or root context.

I believe this should instead say:
@throws JsonGenerationException if this method is not called within an array, root, or field context.

For example, the reference implementation (I believe correctly) allows the following without error:

        JsonGenerator gen = Json.createGenerator(writer);
        gen.writeStartObject();
        gen.writeKey("foo");
        gen.write(Json.createObjectBuilder().build());  // write(JsonValue) in field context
        gen.writeEnd();
        gen.close();

**Comment by m0mus** [comment]
Feel free to submit a PR.
