### ISSUE TITLE
Fix JavaDoc of JsonPatch

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jsonp#143]
The `Operation` enum of `JsonPatch` has an error in the JavaDoc: https://javaee.github.io/javaee-spec/javadocs/javax/json/JsonPatch.Operation.html 
`REPLACE` says
"remove" operation.
Should be 
"replace" operation.

**Comment by jesperdj** [comment]
https://github.com/eclipse-ee4j/jsonp/pull/172

**Comment by AdlerFleurant** [comment]
This issue was fixed by Pull Request: #172
Can someone close this?
