### ISSUE TITLE
Reference implementation shouldn't use exception handling for conditional logic

### ISSUE THREAD

**Issue by jjspiegel** [eclipse-ee4j/jsonp#146]
I noticed code like the following in JsonObjectBuilderImpl.java
```
        @Override
        public String getString(String name, String defaultValue) {
            try {
                return getString(name);
            } catch (Exception e) {
                return defaultValue;
            }
        }
```
It is using exception handling to return the default value in cases where the entry is not present or not a string.  This is not good practice and can be a performance bottleneck as the stack trace is constructed and discarded.   Instead, the code should use a null check on the raw value followed by a check on its value kind if it is not null.

**Comment by jhinch-at-atlassian-com** [comment]
We have observed this performance issue in practice. I would be happy to contribute a fix if you accept pull requests

**Comment by jjspiegel** [comment]
@m0mus do you accept pull requests?

**Comment by Cousjava** [comment]
All Eclipse EE4J projects accept pull requests. You need to have signed the ECA (https://www.eclipse.org/legal/ECA.php) and to sign off your commits (git commit -s).

**Comment by lukasj** [comment]
the process itself is formalized at: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git

**Comment by jhinch-at-atlassian-com** [comment]
Thanks. As promised, I raised a fix. Let me know if you have any questions
