### ISSUE TITLE
Add JsonArrayBuilder getJsonArrayBuilder()/JsonObjectBuilder getJsonObjectBuilder() to JsonArray/JsonObject

### ISSUE THREAD

**Issue by julianomqs** [eclipse-ee4j/jsonp#157]
As far as I know there is no way to modify a `JsonArray `or `JsonObject `after reading it with `JsonReader`.

I would like to read some JSON from strings and change them:

```java
JsonObject jsonObject = Json.createReader(new StringReader("{ \"name\": \"John\", \"age\": \"31\" }")).readObject();
JsonArray jsonArray = Json.createReader(new StringReader("[ \"a\", \"b\", \"c\" ]")).readArray();
```

But `JsonArray `and `JsonObject `are immutable, so I can't do that.

So my suggestion is to add two utilities methods to achieve that:

```java
public interface JsonArray extends JsonStructure, List<JsonValue> {
    JsonArrayBuilder getJsonArrayBuilder();
}
```

```java
public interface JsonObject extends JsonStructure, Map<String, JsonValue> {
    JsonObjectBuilder getJsonObjectBuilder();
}
```
With that two methods would be easier to write and read a JSON code and reducing the verbosity and workarounds.

**Comment by leadpony** [comment]
Hello @julianomqs. 
You can use the API [JsonBuilderFactory#createArrayBuilder](https://static.javadoc.io/javax.json/javax.json-api/1.1.3/javax/json/JsonBuilderFactory.html#createArrayBuilder-javax.json.JsonArray-) and [JsonBuilderFactory#createObjectBuilder](https://static.javadoc.io/javax.json/javax.json-api/1.1.3/javax/json/JsonBuilderFactory.html#createObjectBuilder-javax.json.JsonObject-) to modify the existing JSON array/object.

**Comment by julianomqs** [comment]
I'm really sorry, I forgot to mention I'm using Java EE 7.

I see in Java EE 8 those methods you mentioned are already present in `Json` class.

Closing this issue.

Thanks a lot.
