### ISSUE TITLE
Update JSONP Link

### ISSUE THREAD

**Issue by jjspiegel** [eclipse-ee4j/jsonp#164]
This page:
https://javaee.github.io/jsonp/download.html

Still links to the old github repository.

**Comment by alexsm82** [comment]
That's the old Java EE site, so it links to the old github repo.

**Comment by jjspiegel** [comment]
What is your point?  Are you saying it shouldn't be modified point to the new repository?

**Comment by alexsm82** [comment]
Correct, there will be a new page set up for the Jakarta project.  I believe issue #141 was opened for that.

**Comment by jjspiegel** [comment]
The old github repository has been modified to point to the new one.  The old page comes up high in the search indexes.  Users will find this page and may download old releases as a result.

**Comment by alexsm82** [comment]
@m0mus Any insight here?

**Comment by bshannon** [comment]
Hopefully the web site content will be migrated to the Eclipse project and eventually
the new site will show up higher in searches.  We don't plan to update the old site.

**Comment by jjspiegel** [comment]
I still don't understand why we wouldn't just update the link.  Seems like a low cost fix to something that will very likely confuse people.  But if you are unwilling to make this change you can close this issue accordingly.
