### ISSUE TITLE
Update Scope Statement for Jakarta API for JSON Processing Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jsonp#166]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by m0mus** [comment]
Proposed new scope:

Jakarta API for JSON Binding provides a specification document, API and TCK that define a Java(R) based framework for parsing, generating, transforming, and querying JSON documents.

**Comment by waynebeaton** [comment]
The name (#167) will likely be "Jakarta JSON Processing". 

How about:

> Jakarta JSON Processing defines a Java(R) based framework for parsing, generating, transforming, and querying JSON documents.
