### ISSUE TITLE
Change project name to Jakarta JSON Processing

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jsonp#167]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub (including the project settings)
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j
- [x] Project site https://eclipse-ee4j.github.io/jsonp/

**Comment by ivargrimstad** [comment]
Any objections to the name "Jakarta JSON Processing"?

**Comment by keilw** [comment]
Nope

**Comment by m0mus** [comment]
No objections
