### ISSUE TITLE
Json.createObjectBuilder(Map) has impractical type bounds

### ISSUE THREAD

**Issue by pdudits** [eclipse-ee4j/jsonp#168]
The definition `Json.createObjectBuilder(Map<String,Object> map)` is quite limiting for object construction, as the value type parameter of Map must be Object.

For example I cannot simply convert a `Map<String,String>` into json via this method as javac rightfully complains "Cannot find resolve method `createObjectBuilder(Map<String,String>)`.  In order to workaround this, one must use raw type cast `createObjectBuilder((Map)stringsMap)`.

I believe the correct API would be `createObjectBuilder(Map<String,?>)` just like config factory methods are.

Such change would break source compatibility of providers, but it is binary compatible change for users, so the impact is not high.

**Comment by lukasj** [comment]
done
