### ISSUE TITLE
JsonValue of JsonArray without quotation marks

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/jsonp#200]
I have a json array:

[
    "TASK_1"
    "TASK_2",
    "TASK_3"
]

and want to de-serialize it:

```
var set = EnumSet.noneOf(Task.class);
try (var jsonReader = Json.createReader(new StringReader(json))) {
      jsonReader.readArray().forEach(v -> {
      // returns "TASK_1" instead of TASK_1 (without double quotes)
     log.info("v="+v);
     // throws exception, because v.toString returns value with double quotes
     set.add(Enum.valueOf(Task.class, v.toString()));
});
}
```

So the json-value is returned with "quotation marks", but I need it without. 

A method something like

`JsonValue#getString(boolean withoutQuotes)` 

would be nice.

**Btw, the Json-P default behaviour of a string value should be to return a string without quotation marks, but in Arrays the default behaviour does not work.**

**Comment by leadpony** [comment]
Hello @nimo23 
`JsonString#getString()` is available for your purpose.

```java
String json = "[\"TASK_1\", \"TASK_2\", \"TASK_3\"]";
EnumSet<Task> set = EnumSet.noneOf(Task.class);
try (JsonReader reader = Json.createReader(new StringReader(json))) {
    reader.readArray().forEach(v -> {
        String string = ((JsonString) v).getString();
        set.add(Task.valueOf(string));
    });
}
```
`JsonValue#toString()` is for obtaining JSON representation of the value.

**Comment by nimo23** [comment]
Hello @leadpony thanks!
