### ISSUE TITLE
Build fails for jakarta.json-api:jar:1.1.6

### ISSUE THREAD

**Issue by rakeshk15** [eclipse-ee4j/jsonp#210]
I have updated my pom to have v1.1.6 of jakarta.json-api but the build fails with this error - **Failure to find org.glassfish:json:pom:1.1.6**

org.glassfish:json:pom:1.1.6 is declared parent of  jakarta.json-api but it seems it is missing from central.

[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.adeptj:adeptj-runtime >----------------------
[INFO] Building AdeptJ Runtime 1.0.14-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.373 s
[INFO] Finished at: 2019-08-30T21:07:48+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project adeptj-runtime: Could not resolve dependencies for project com.adeptj:adeptj-runtime:jar:1.0.14-SNAPSHOT: Failed to collect dependencies at jakarta.json:jakarta.json-api:jar:1.1.6: Failed to read artifact descriptor for jakarta.json:jakarta.json-api:jar:1.1.6: Failure to find org.glassfish:json:pom:1.1.6 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by senivam** [comment]
seems to be resolved for now
