### ISSUE TITLE
Compatibility Certification Request for Eclipse JSON Processing 2.0.0

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jsonp#257]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  [Eclipse JSON Processing 2.0.0](https://eclipse-ee4j.github.io/jsonp)
- [x] Specification Name, Version and download URL\
   [Jakarta JSON Processing 2.0](https://jakarta.ee/specifications/jsonp/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL\
  [Jakarta JSON Processing TCK 2.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jsonp-tck-2.0.0.zip), SHA-256: 457f557667eb5ca5e28507b8aae92b25dd69a1177b85b81b65339f322a70989b
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/jsonp/tck/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by lukasj** [comment]
accepted
