### ISSUE TITLE
Compatibility Certification Request for Joy 2.1.0

### ISSUE THREAD

**Issue by leadpony** [eclipse-ee4j/jsonp#271]
- [x] Organization Name ("Organization") and, if applicable, URL
  [leadpony.org](https://github.com/leadpony)
- [x] Product Name, Version and download URL (if applicable)
  [Joy 2.1.0](https://leadpony.github.io/joy)
- [x] Specification Name, Version and download URL
   [Jakarta JSON Processing 2.0](https://jakarta.ee/specifications/jsonp/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta JSON Processing TCK 2.0.0](http://download.eclipse.org/jakartaee/jsonp/2.0/jakarta-jsonp-tck-2.0.0.zip), SHA-256: 457f557667eb5ca5e28507b8aae92b25dd69a1177b85b81b65339f322a70989b
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://leadpony.github.io/joy/tck/report.html)
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  OpenJDK 1.8.0 Update 275, vendor: Red Hat, Inc.
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

TCK 2.0.0 results summary:
```
Completed running 187 tests.
Number of Tests Passed = 187
Number of Tests Failed = 0
Number of Tests with Errors = 0
```

Could you please accept my request?

**Comment by m0mus** [comment]
Accepted. Thanks for bringing another implementation!!!

**Comment by Thihup** [comment]
@m0mus Do you know what is needed for a Compatible Implementation to show here? https://jakarta.ee/specifications/jsonp/2.0/

**Comment by leadpony** [comment]
@m0mus 
Thank you a lot. 
Can I send a PR at https://github.com/jakartaee/specifications to update https://github.com/jakartaee/specifications/blob/master/jsonp/2.0/_index.md?

**Comment by m0mus** [comment]
@Thihup This page contains an implementation which was used to prove the spec is implementable for the ballot. There were thoughts of extending Jakarta pages to list other implementations, but I don't know the status of that work. I'll be happy to provide some marking support for your implementation by tweeting about it.
