### ISSUE TITLE
JsonParser needs to have a way to get current event

### ISSUE THREAD

**Issue by Verdent** [eclipse-ee4j/jsonp#282]
It would be nice to have a way how to re-obtain the event which was thrown the last by JsonParser.

Something like method `JsonParser.Event current()` or `JsonParser.Event currentEvent()`.

**Comment by jjspiegel** [comment]
Not opposed. StAX has this:
https://docs.oracle.com/javase/7/docs/api/javax/xml/stream/XMLStreamReader.html#getEventType()

**Comment by jbescos** [comment]
- [ ] TCK
