### ISSUE TITLE
New name for the implementation project/repo split

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jsonp#285]
I'm about to set new name for the implementation project eventually.

I suggest keep using `Eclipse JSONP`.

Alternative names:

* `jsonp4j`
* `Parson`
* `Parsson`

Does anyone have ideas and/or suggestions for something else?

Since this requires involvement or other teams within Eclipse Fnd, I'm also about to ask for splitting the project into 3 repositories - one for API, one for the TCK and one for the implementation project unless there is strong opinion on not doing so. Comments on how this change should be done are welcomed - I can see also an option to have API and TCK in one repo and implementation in the other.

Silence within the next week means that I'll go with my preference but I would really prefer to get wider consensus on this.

I would like to bring this up to appropriate places for approval by the next Friday, April 30 2021.

**Comment by jbescos** [comment]
Name is fine with me.

I like more to have API and TCK in the same repository. This is convenient because we don't need to release a new API in maven to make TCK test sto work with the changes.

**Comment by dalexandrov** [comment]
I really like Parson

**Comment by jjspiegel** [comment]
I am in favor of putting the API in a separate repository, especially if this means that it versions independently.  Right now it is troublesome for projects that only depend on the API because the version appears to move so frequently even when nothing has changed.  

I also like your suggestion of "Eclipse JSONP".

**Comment by keilw** [comment]
I think the API should be separate similar to jsonb, and since that got its own dedicated implementation project name "Yasson" I would prefer "Parson" (if "Parsson" like "Yasson" made it easier to avoid any brand conflict, why not) because of both
- https://de.wikipedia.org/wiki/Alan_Parsons
- https://de.wikipedia.org/wiki/Jim_Parsons

**Comment by waynebeaton** [comment]
> I think the API should be separate similar to jsonb, and since that got its own dedicated implementation project name "Yasson" I would prefer "Parson" (if "Parsson" like "Yasson" made it easier to avoid a brand conflict, why not) because of both

Determining whether or not we can use a name depends on how we intend to use a name and how it is used by others. Generally, the selection of name is about avoiding confusion and it's not always obvious. The simple check is to try searching for "<name> technology" using your favourite search engine to see what comes up; even if you do find other technologies with the same name, if a case can be made that an average person would not confuse our project's use with that hypothetical other hit's use, then it may be okay. Just spelling a word differently doesn't always get you off the hook (we couldn't reasonably try to claim that a project name "Hadooop" is distinct from "Hadoop"). Of course, completely distinct names are always best.

We'll run whatever you come up with past the Trademarks Team who will take care of checking against the EUIPO, USPTO, etc. It's always good to have a couple of options to fall back on.

**Comment by lukasj** [comment]
reminder:

I go with names in following order:
* Parsson
* Eclipse JSONP
* jsonp4j

and with following repo split:
* API + TCK
* implementation

unless I hear otherwise or some other suggestions.

**Comment by lukasj** [comment]
proposal is at https://projects.eclipse.org/proposals/eclipse-parsson
