### ISSUE TITLE
When patching jsonarray of json object by adding new json object, invalid json is constructed

### ISSUE THREAD

**Issue by gterseglav** [eclipse-ee4j/jsonp#301]
When patching jsonarray of json object by adding new json object, invalid json is constructed.

**Original json:**
        String inputJavaJsonString = "{\"contactMediums\":[ " +
                "{\"mediumCharacteristic\":{\"emailAddress\":\"user@email.com\"},\"mediumType\":\"EMAIL_ADDRESS\"}]," +
                "\"id\":1}\n";
        JsonReader jsonReader = Json.createReader(new StringReader(inputJavaJsonString));
        JsonObject inputJavaJsonObject = jsonReader.readObject();

**Patch code:**
        JsonPatch jsonPatch = Json.createPatchBuilder()
                .add("/contactMediums/-", newContactMediumJsonObject.toString())
                .build();
        JsonObject patchedJsonObject = jsonPatch.apply(inputJavaJsonObject);

Created patchedJsonObject contains malformed content.

**_Steps to reproduce:_**

**1) Add following json maven libs**

    <dependency>
      <groupId>org.glassfish</groupId>
      <artifactId>jakarta.json</artifactId>
      <version>2.0.1</version>
    </dependency>
    <dependency>
      <groupId>jakarta.json.bind</groupId>
      <artifactId>jakarta.json.bind-api</artifactId>
      <version>2.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse</groupId>
      <artifactId>yasson</artifactId>
      <version>2.0.2</version>
    </dependency>

**2) Add following method/unit test**

    @Test
    void test4() {
        String inputJavaJsonString = "{\"contactMediums\":[ " +
                "{\"mediumCharacteristic\":{\"emailAddress\":\"user@email.com\"},\"mediumType\":\"EMAIL_ADDRESS\"}]," +
                "\"id\":1}\n";
        JsonReader jsonReader = Json.createReader(new StringReader(inputJavaJsonString));
        JsonObject inputJavaJsonObject = jsonReader.readObject();

        JsonObject newContactMediumJsonObject = Json.createObjectBuilder()
                .add("mediumType", "PHONE_NUMBER")
                .add("mediumCharacteristic", Json.createObjectBuilder()
                        .add("phoneNumber", "123 123 003")
                        .add("contactType", "PHONE_NUMBER")
                        .build())
                .build();

        JsonPatch jsonPatch = Json.createPatchBuilder()
                .add("/contactMediums/-", newContactMediumJsonObject.toString())
                .build();
        JsonObject patchedJsonObject = jsonPatch.apply(inputJavaJsonObject);

        System.out.println("input java object json string:");
        System.out.println(inputJavaJsonString);

        System.out.println("patched java object json string:");
        String unescapedPatchedJsonObject = patchedJsonObject.toString().replaceAll("\\\\","");
        System.out.println(unescapedPatchedJsonObject);
    }

**3) Execute method/unit test**

**4) Observe output**

input java object json string:
`
{"contactMediums":[ {"mediumCharacteristic":{"emailAddress":"user@email.com"},"mediumType":"EMAIL_ADDRESS"}],"id":1}
`
patched java object json string:
`
{"contactMediums":[{"mediumCharacteristic":{"emailAddress":"user@email.com"},"mediumType":"EMAIL_ADDRESS"},"{"mediumType":"PHONE_NUMBER","mediumCharacteristic":{"phoneNumber":"123 123 003","contactType":"PHONE_NUMBER"}}"],"id":1}
`

You can see that inserted json object is enclosed in double quotes. If you try to verify patched json using https://jsonformatter.curiousconcept.com/#, it returns error. If you remove enclosing quotes, verify confirms json structure.

**5) Expected json patch structure with double quotes removed**
`
{"contactMediums":[{"mediumCharacteristic":{"emailAddress":"user@email.com"},"mediumType":"EMAIL_ADDRESS"},{"mediumType":"PHONE_NUMBER","mediumCharacteristic":{"phoneNumber":"123 123 003","contactType":"PHONE_NUMBER"}}],"id":1}
`

**Comment by gterseglav** [comment]
Workaround:
Fix malformed json by removing double quotes. 

Add following code to the end of the code block:
        String removedFirstDoubleQuote = unescapedPatchedJsonObject.replaceAll("\"\\{", "{");
        System.out.println(removedFirstDoubleQuote);
        String removedSecondDoubleQuote = removedFirstDoubleQuote.replaceAll("}\"", "}");
        System.out.println(removedSecondDoubleQuote);

Now json is verified.

**Comment by jbescos** [comment]
You can also make it work in this way:
```
        JsonPatch jsonPatch = Json.createPatchBuilder()
                .add("/contactMediums/-", newContactMediumJsonObject)
                .build();
```

Note there is no `newContactMediumJsonObject.toString()`

**Comment by jbescos** [comment]
I have prepared one fix to make it work with toString(), but then there is other test that verifies that is failing (JsonPatchBuilderTest#shouldBuildJsonPatchExpressionUsingJsonPatchBuilder).

It seems that method `JsonPatchBuilderImpl.add(String path, String value)` is not expecting a JSON string as value, although the javadoc does not say too much.

I think it is working fine as it is right now.

**Comment by gterseglav** [comment]
Thanks. I will try with your suggestion and get back.

**Comment by gterseglav** [comment]
If I remove toString() as suggested, problem with added double quotes is gone. Also problem with escape characters '\' that toString() introduces for each double quote is gone. Instruction for all with the same problem would be not to use toString(), when you use JsonPatch.add() method.
