### ISSUE TITLE
Are there any docs about how to create an implementation?

### ISSUE THREAD

**Issue by toddobryan** [eclipse-ee4j/jsonp#375]
I'd like to try to provide an implementation in Kotlin using the `kotlinx-serialization` JSON library. But I'm not sure how to start.

My guess is that you have to provide some implementations and others just depend on those, but is that documented anywhere or is it just a matter of going through the code, adding implementations, and repeating until your code compiles and passes the tests?

**Comment by lukasj** [comment]
To provide an implementation, the [SPI/JsonProvider](https://jakarta.ee/specifications/jsonp/2.1/apidocs/jakarta.json/jakarta/json/spi/jsonprovider) is the starting point
