### ISSUE TITLE
Are we going to keep Groups.io?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jsonp#85]
The [JavaDoc](https://javadoc.io/doc/javax.json/javax.json-api/1.1.2) and maybe other places mention jsonp-spec@javaee.groups.io for comments or questions. Are we going to keep javaee.groups.io? Especially because of the whole branding issue, it is unlikely, so if there is an adequate replacement, this new mailing list should be put into JavaDoc and similar places instead.

**Comment by m0mus** [comment]
I am working on changing javaee domain in groups.io to jakartaee. But, to be honest, I prefer using jsonp-dev@eclipse.org mailing list and GitHub issues tracker for communication. What do others think?

**Comment by m0mus** [comment]
@keilw Shall we close it?

**Comment by keilw** [comment]
If a new mailing list is there or planned for sure, then yes, it was also a question.

**Comment by keilw** [comment]
Have you deleted the old group or is there a way to make it read-only?
