### ISSUE TITLE
Contributors to Wiki?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jsonp#86]
I noticed someone just created a Wiki: https://github.com/eclipse-ee4j/jsonp/wiki

That's nice. In java.net times most JSRs allowed to contribute to that wiki for at least every EG member/committer. Is this also the intention here? I know the eclipse.org wiki normally won't be restricted to committers, at most you need a user account and an ECA signed. I see no edit or create page actions for this wiki.

**Comment by m0mus** [comment]
Access rights fixed.
